export const defaultShortcuts = {
  mapMidi: "m",
  cancelMap: "Escape",
  pickDrop: "p",
  removeLfoModFromFocusedSlider: "Shift+p",
  toggleAnnounceMode: "Shift+a",
  startVoice: "v",
  sliderMin: "1",
  sliderMax: "2",
  sliderDefault: "0",
  sliderX10Left: "Shift+ArrowLeft",
  sliderX10Right: "Shift+ArrowRight",
  sliderX100Left: "Control+Shift+ArrowLeft",
  sliderX100Right: "Control+Shift+ArrowRight",
  goToOsc: "Alt+c",
  goToFilter: "Alt+v",
  goToEnv: "Alt+b",
  goToFx: "Alt+n",
  goToLFO: "Alt+m",
};
