export const defaultShortcuts = {
  mapMidi: "KeyM",
  cancelMap: "Escape",
  pickDrop: "KeyP",
  removeMod: "Shift+KeyP",
  toggleAnnounce: "Shift+KeyA",
  startVoice: "KeyV",
  sliderMin: "Shift+Digit1",
  sliderMax: "Shift+Digit2",
  sliderDefault: "Shift+Digit0",
  sliderX10Left: "Shift+ArrowLeft",
  sliderX10Right: "Shift+ArrowRight",
  sliderX100Left: "Control+Shift+ArrowLeft",
  sliderX100Right: "Control+Shift+ArrowRight",
  goToGlobal: "Alt+KeyZ",
  goToOsc: "Alt+KeyX",
  goToFilter: "Alt+KeyC",
  goToModEnv: "Alt+KeyV",
  goToLFO: "Alt+KeyB",
  goToAddFx: "Alt+KeyN",
  goToFxChain: "Alt+KeyM",
};
