export const MPE_DEST_OPTIONS = {
  pitchBendDest: [
    { value: "pitch", label: "Pitch" },
    { value: "vectorX", label: "Vector X" },
    { value: "vectorY", label: "Vector Y" },
    { value: "detune", label: "Osc Detune" },
    { value: "pan", label: "Pan" },
    { value: "filter", label: "Filter Cutoff" },
    { value: "volume", label: "Volume" },
    { value: "resonance", label: "Resonance" },
  ],
  aftertouchDest: [
    { value: "filter", label: "Filter Cutoff" },
    { value: "volume", label: "Volume" },
    { value: "pan", label: "Pan" },
    { value: "vectorX", label: "Vector X" },
    { value: "vectorY", label: "Vector Y" },
    { value: "resonance", label: "Resonance" },
  ],
  modWheelDest: [
    { value: "filter", label: "Filter Cutoff" },
    { value: "volume", label: "Volume" },
    { value: "pan", label: "Pan" },
    { value: "vectorX", label: "Vector X" },
    { value: "vectorY", label: "Vector Y" },
    { value: "resonance", label: "Resonance" },
  ],
  slideDest: [
    { value: "vectorX", label: "Vector X" },
    { value: "vectorY", label: "Vector Y" },
    { value: "detune", label: "Osc Detune" },
    { value: "pan", label: "Pan" },
    { value: "filter", label: "Filter Cutoff" },
    { value: "volume", label: "Volume" },
    { value: "resonance", label: "Resonance" },
  ],
};
